# Generated by Django 4.1.1 on 2022-09-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='courses', to='courses.course')),
            ],
        ),
    ]
