# Generated by Django 4.1.1 on 2022-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_seat_course_all_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quota',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Course Name'),
        ),
    ]
