# Generated by Django 4.1.1 on 2022-09-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
