# Generated by Django 4.1.1 on 2022-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
