# Generated by Django 4.1.1 on 2022-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_total_seat_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quota_seat',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
