# Generated by Django 4.1.1 on 2022-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_quota_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quota_seat',
            field=models.BooleanField(default=True, verbose_name='Seat Available'),
        ),
    ]
