# Generated by Django 4.1.1 on 2022-09-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
